### ISSUE TITLE
エラー

### ISSUE THREAD

**Issue by yaakiyu** [free-RT/rt-bot#99]
忙しいのでメモだけで。
```python
Ignoring exception in view <EmbedPage timeout=180.0 children=4> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='▶️' id=None> row=None>:
Traceback (most recent call last):
  File "C:\Users\yaakiyu\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py", line 414, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\yaakiyu\rt-bot\util\page.py", line 33, in right
    await self.on_turn("r", interaction)
  File "C:\Users\yaakiyu\rt-bot\util\page.py", line 63, in on_turn
    await interaction.response.edit_message(embed=embed, **self.on_page())
AttributeError: 'Button' object has no attribute 'response'
Ignoring exception in view <EmbedPage timeout=180.0 children=4> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏩' id=None> row=None>:
Traceback (most recent call last):
  File "C:\Users\yaakiyu\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py", line 414, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\yaakiyu\rt-bot\util\page.py", line 37, in dash_right
    await self.on_turn("dr", interaction)
  File "C:\Users\yaakiyu\rt-bot\util\page.py", line 63, in on_turn
    await interaction.response.edit_message(embed=embed, **self.on_page())
AttributeError: 'Button' object has no attribute 'response'
C:\Users\yaakiyu\rt-bot\cogs\servertool\thread_manager\dataclass.py:59: RuntimeWarning: coroutine 'Event.wait' was never awaited
  await wait_for(self.lock.wait(), 6, loop=self.cog.bot.loop)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Ignoring exception in on_thread_update
Traceback (most recent call last):
  File "C:\Users\yaakiyu\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 375, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\yaakiyu\rt-bot\cogs\servertool\thread_manager\__init__.py", line 368, in on_thread_update
    and after.parent.id in await (
  File "C:\Users\yaakiyu\rt-bot\cogs\servertool\thread_manager\dataclass.py", line 59, in new_coro
    await wait_for(self.lock.wait(), 6, loop=self.cog.bot.loop)
TypeError: wait_for() got an unexpected keyword argument 'loop'
```

**Comment by HardSmoothy** [comment]
なんかutil\page.pyの33,37,63行目で「Button.responseがねぇぜ兄貴！」って言ってる気がする。
あとwait_for(loop)ってあるのか...?

**Comment by yaakiyu** [comment]
①おそらくbuttonとinteractionの引数の順番に関する破壊的変更を適応してない。
②loop引数はpython3.10で削除された。
直す

**Comment by yaakiyu** [comment]
修正した。
